"""test2

Revision ID: 7abc0e46d835
Revises: 80831eeca715
Create Date: 2023-05-03 14:20:49.487911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7abc0e46d835'
down_revision = '80831eeca715'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('stats_search_id_key', 'stats_search', type_='unique')
    op.drop_column('stats_search', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stats_search', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_unique_constraint('stats_search_id_key', 'stats_search', ['id'])
    # ### end Alembic commands ###
