"""initi
al check

Revision ID: 901eee9255e1
Revises: 
Create Date: 2023-05-03 14:15:15.046229

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '901eee9255e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('couriers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('user_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('city_from', sa.VARCHAR(length=25), nullable=False),
    sa.Column('city_to', sa.VARCHAR(length=25), nullable=False),
    sa.Column('flight_date', sa.DATE(), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=False),
    sa.Column('info', sa.VARCHAR(length=200), nullable=False),
    sa.Column('status', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_table('search_couriers')
    op.create_unique_constraint(None, 'blacklist', ['user_id'])
    op.drop_column('blacklist', 'id')
    op.alter_column('stats', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_unique_constraint(None, 'stats', ['user_id'])
    op.drop_column('stats', 'id')
    op.add_column('stats_search', sa.Column('stat_id', sa.Integer(), nullable=True))
    op.alter_column('stats_search', 'city_from',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('stats_search', 'city_to',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('stats_search', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_unique_constraint(None, 'stats_search', ['stat_id'])
    op.drop_column('stats_search', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stats_search', sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=True, cache=1), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'stats_search', type_='unique')
    op.alter_column('stats_search', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('stats_search', 'city_to',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('stats_search', 'city_from',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_column('stats_search', 'stat_id')
    op.add_column('stats', sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=True, cache=1), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'stats', type_='unique')
    op.alter_column('stats', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('blacklist', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'blacklist', type_='unique')
    op.create_table('search_couriers',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('user_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('dest', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('flight_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('extra', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='search_couriers_pkey')
    )
    op.drop_table('couriers')
    # ### end Alembic commands ###
