"""test3

Revision ID: bebe7998fd4d
Revises: 7abc0e46d835
Create Date: 2023-05-03 14:33:31.745841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bebe7998fd4d'
down_revision = '7abc0e46d835'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
